version = "0.1"

[[services]]
  name = "frontend"
  language = "javascript"
  build = "npm run build"
  start = "npm start"
  entrypoint = "frontend"
  env = { NODE_ENV = "production" }

[[services]]
  name = "backend"
  language = "javascript"
  start = "npm start"
  entrypoint = "backend"
  env = { NODE_ENV = "production" }